### ISSUE TITLE
BODY OPENEN IN HEAD

### ISSUE THREAD

**Issue by IvarSchuyt** [kosterm14/server-side-rendering#2]
https://github.com/kosterm14/server-side-rendering/blob/0c8fe92761843c82042b6aa98e82ea311551d800/views/index.ejs#L3

**Comment by IvarSchuyt** [comment]
EN SLUITEN IN FOOT

**Comment by kosterm14** [comment]
dank je ik wist niet dat dat moest maar nu je het zegt klinkt het heel logisch ik heb het gefixt hoor
