### ISSUE TITLE
responsiveness 

### ISSUE THREAD

**Issue by RayanSp** [kosterm14/server-side-rendering#4]
Er gaat veel buiten beeld wanneer ik je website op mobile bekijk, je kan dit nog op lossen met media-queries maar dat gaat wel tijd kosten. Ik denk dat het handig is dat je de volgende keer mobile first begint.

**Comment by kosterm14** [comment]
Hier had ik helaas geen tijd voor maar ik zal dit zeker meenemen naar een volgende sprint
